---
kind: pipeline
name: build
type: docker

steps:
  - name: build_kibana
    image: plugins/docker
    privileged: true
    network_mode: host
    custom_dns: [1.1.1.1, 9.9.9.9]
    settings:
      auto_tag: true
      auto_tag_suffix: latest
      repo: beehivesec/kibana
      cache_from: blackhatch/kibana:latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        - push
        - tag
 